apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: sonarqube
spec:
  virtualhost:
    fqdn: sonarqube.sandbox.futures.army
    tls:
      secretName: tls-secret
  routes:
  - services:
    - name: sonarqube-sonarqube
      port: 9000
    conditions:
    - prefix: /
